# Generated by Django 5.0.6 on 2024-07-26 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Greenhouse',
            fields=[
                ('GreenhouseID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=50)),
                ('Username', models.CharField(max_length=50)),
                ('DateJoined', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Ecosystem',
            fields=[
                ('EcosystemID', models.AutoField(primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=1000)),
                ('Greenhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.greenhouse')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('LocationID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Region', models.CharField(max_length=150)),
                ('Climate', models.CharField(max_length=50)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('Ecosystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ecosystem')),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('PlantID', models.AutoField(primary_key=True, serialize=False)),
                ('DatePlanted', models.DateField()),
                ('Height', models.FloatField()),
                ('Greenhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.greenhouse')),
            ],
        ),
        migrations.CreateModel(
            name='PlantLifeCycle',
            fields=[
                ('PlantLifeCycleID', models.AutoField(primary_key=True, serialize=False)),
                ('GerminationDate', models.DateField()),
                ('MaturityDate', models.DateField()),
                ('Plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.plant')),
            ],
        ),
        migrations.CreateModel(
            name='PlantNutrientLevel',
            fields=[
                ('PlantNutrientLevelID', models.AutoField(primary_key=True, serialize=False)),
                ('Nitrogen', models.FloatField()),
                ('Phosphorus', models.FloatField()),
                ('Potassium', models.FloatField()),
                ('Plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.plant')),
            ],
        ),
        migrations.CreateModel(
            name='Specie',
            fields=[
                ('SpecieID', models.AutoField(primary_key=True, serialize=False)),
                ('CommonName', models.CharField(max_length=50)),
                ('ScientificName', models.CharField(max_length=50)),
                ('Plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.plant')),
            ],
        ),
        migrations.CreateModel(
            name='PlantHarvest',
            fields=[
                ('PlantHarvestID', models.AutoField(primary_key=True, serialize=False)),
                ('DateHarvested', models.DateTimeField()),
                ('Specie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.specie')),
            ],
        ),
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('TerrainID', models.AutoField(primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=50)),
                ('Features', models.CharField(max_length=1000)),
                ('Ecosystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ecosystem')),
            ],
        ),
        migrations.CreateModel(
            name='SoilType',
            fields=[
                ('SoilTypeID', models.AutoField(primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=50)),
                ('Terrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.terrain')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('PhotoID', models.AutoField(primary_key=True, serialize=False)),
                ('DateTaken', models.DateTimeField()),
                ('Plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.plant')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('VisitID', models.AutoField(primary_key=True, serialize=False)),
                ('Greenhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.greenhouse')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='VisitPrice',
            fields=[
                ('VisitPriceID', models.AutoField(primary_key=True, serialize=False)),
                ('Price', models.FloatField()),
                ('Visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.visit')),
            ],
        ),
        migrations.CreateModel(
            name='VisitTime',
            fields=[
                ('VisitTimeID', models.AutoField(primary_key=True, serialize=False)),
                ('Duration', models.IntegerField()),
                ('Visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.visit')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherDate',
            fields=[
                ('WeatherDateID', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Temperature', models.FloatField()),
                ('Precipitation', models.FloatField()),
                ('Humidity', models.IntegerField()),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.location')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('WorkerID', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateTimeField()),
                ('WorkHours', models.IntegerField()),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='Watering',
            fields=[
                ('WateringID', models.AutoField(primary_key=True, serialize=False)),
                ('Frequency', models.IntegerField()),
                ('LastWatered', models.DateTimeField()),
                ('Plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.plant')),
                ('Worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Pesticide',
            fields=[
                ('PesticideID', models.AutoField(primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=50)),
                ('Date', models.DateTimeField()),
                ('Plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.plant')),
                ('Worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.worker')),
            ],
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('WorkScheduleID', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateTimeField()),
                ('WorkHours', models.IntegerField()),
                ('Worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.worker')),
            ],
        ),
    ]
